export const RELATIONSHIP_STATUS_MARRIED = "married"
export const RELATIONSHIP_STATUS_PARTNER = "partner"
const RELATIONSHIP_STATUS_DIVORCED = "divorced"
const RELATIONSHIP_STATUS_SINGLE = "single"
const RELATIONSHIP_STATUS_WIDOW = "widow"
const RELATIONSHIP_STATUS_SEPARATED = "separated"

export const hasPartner = relationshipStatus =>
  [RELATIONSHIP_STATUS_MARRIED, RELATIONSHIP_STATUS_PARTNER].indexOf(
    relationshipStatus
  ) !== -1

export default [
  { key: "RELATIONSHIP_STATUS_MARRIED", value: RELATIONSHIP_STATUS_MARRIED },
  { key: "RELATIONSHIP_STATUS_PARTNER", value: RELATIONSHIP_STATUS_PARTNER },
  { key: "RELATIONSHIP_STATUS_DIVORCED", value: RELATIONSHIP_STATUS_DIVORCED },
  { key: "RELATIONSHIP_STATUS_SINGLE", value: RELATIONSHIP_STATUS_SINGLE },
  { key: "RELATIONSHIP_STATUS_WIDOW", value: RELATIONSHIP_STATUS_WIDOW },
  { key: "RELATIONSHIP_STATUS_SEPARATED", value: RELATIONSHIP_STATUS_SEPARATED }
]
