export { inverseLerp } from "./inverseLerp/inverseLerp"
export { lerp } from "./lerp/lerp"
export { cosineInterpolate } from "./cosineInterpolate/cosineInterpolate"
export { clamp } from "./clamp/clamp"
export { multiplyPixelValue } from "./multiplyPixelValue/multiplyPixelValue"
export { isNumber } from "./isNumber/isNumber"
export { almostEquals } from "./almostEquals/almostEquals"
